"use server";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/dark-mode-button";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full min-h-screen flex flex-col`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="bg-customprimarylight dark:bg-customprimarydark flex-grow h-full w-full">
            {children}
          </div>
          <footer className="bg-white dark:bg-black dark:text-white py-4 text-center mt-auto flex flex-row justify-center gap-4 align-center stycky bottom-0">
            <span className="content-center">Gabriele Santoro@2025</span>
            <ModeToggle />
          </footer>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
